-- 네이버 스마트스토어 결제 주문의 디자인 자동 접수 원장.
-- 기존 orders/order_items에는 어떤 데이터도 쓰지 않는다.

create table if not exists public.naver_design_sessions (
  id uuid primary key default gen_random_uuid(),
  naver_order_id text not null unique,
  token_hash text not null unique,
  buyer_name text,
  buyer_phone text,
  receiver_phone text,
  status text not null default 'draft'
    check (status in ('draft', 'in_progress', 'submitted', 'reviewed', 'revision_requested', 'approved', 'cancelled')),
  job_count integer not null default 0 check (job_count >= 0),
  submitted_job_count integer not null default 0 check (submitted_job_count >= 0),
  expires_at timestamptz not null default (now() + interval '30 days'),
  first_viewed_at timestamptz,
  last_viewed_at timestamptz,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.naver_design_jobs (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.naver_design_sessions(id) on delete cascade,
  group_key text not null,
  local_product_id uuid references public.products(id) on delete set null,
  color_code text,
  product_name text not null,
  option_summary text,
  quantity integer not null default 0 check (quantity >= 0),
  product_order_ids text[] not null default '{}'::text[],
  status text not null default 'draft'
    check (status in ('needs_mapping', 'draft', 'in_progress', 'submitted', 'reviewed', 'revision_requested', 'approved', 'cancelled')),
  canvas_state jsonb not null default '{}'::jsonb,
  product_color text,
  customer_note text,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, group_key)
);

create table if not exists public.naver_design_job_claims (
  product_order_id text primary key references public.naver_product_orders(product_order_id) on delete cascade,
  job_id uuid not null references public.naver_design_jobs(id) on delete cascade,
  claimed_at timestamptz not null default now()
);

create table if not exists public.naver_design_assets (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.naver_design_jobs(id) on delete cascade,
  storage_bucket text not null default 'naver-design-assets',
  storage_path text not null unique,
  asset_kind text not null check (asset_kind in ('original', 'processed', 'preview')),
  original_name text not null,
  content_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.naver_design_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.naver_design_sessions(id) on delete cascade,
  job_id uuid references public.naver_design_jobs(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.naver_design_notification_outbox (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null unique references public.naver_design_sessions(id) on delete cascade,
  recipient_phone text,
  template_key text not null default 'SOLAPI_TPL_NAVER_DESIGN_INTAKE',
  variables jsonb not null default '{}'::jsonb,
  status text not null default 'pending'
    check (status in ('pending', 'sending', 'sent', 'failed', 'skipped_no_phone')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  claimed_at timestamptz,
  sent_at timestamptz,
  message_id text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_naver_design_jobs_session_status
  on public.naver_design_jobs(session_id, status);
create index if not exists idx_naver_design_assets_job
  on public.naver_design_assets(job_id, created_at desc);
create index if not exists idx_naver_design_events_session
  on public.naver_design_events(session_id, created_at desc);
create index if not exists idx_naver_design_outbox_pending
  on public.naver_design_notification_outbox(next_attempt_at, created_at)
  where status in ('pending', 'failed');

create or replace function public.ingest_naver_design_order(
  p_naver_order_id text,
  p_token_hash text,
  p_intake_url text,
  p_buyer_name text,
  p_buyer_phone text,
  p_receiver_phone text,
  p_notification_phone text,
  p_items jsonb
)
returns table(session_id uuid, session_created boolean, jobs_created integer, items_claimed integer)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_session_id uuid;
  v_session_created boolean := false;
  v_job_id uuid;
  v_jobs_created integer := 0;
  v_items_claimed integer := 0;
  v_item jsonb;
  v_job_was_created boolean;
  v_phone text;
begin
  if nullif(trim(p_naver_order_id), '') is null then
    raise exception 'naver_order_id is required';
  end if;
  if nullif(trim(p_token_hash), '') is null then
    raise exception 'token_hash is required';
  end if;
  if jsonb_typeof(p_items) <> 'array' then
    raise exception 'items must be a JSON array';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_naver_order_id, 0));

  select id into v_session_id
  from public.naver_design_sessions
  where naver_order_id = p_naver_order_id
  for update;

  if v_session_id is null then
    insert into public.naver_design_sessions (
      naver_order_id, token_hash, buyer_name, buyer_phone, receiver_phone
    ) values (
      p_naver_order_id, p_token_hash, nullif(trim(p_buyer_name), ''),
      nullif(trim(p_buyer_phone), ''), nullif(trim(p_receiver_phone), '')
    )
    returning id into v_session_id;
    v_session_created := true;

    v_phone := nullif(regexp_replace(coalesce(p_notification_phone, ''), '[^0-9]', '', 'g'), '');
    insert into public.naver_design_notification_outbox (
      session_id, recipient_phone, variables, status
    ) values (
      v_session_id,
      v_phone,
      jsonb_build_object(
        '고객명', coalesce(nullif(trim(p_buyer_name), ''), '고객'),
        '주문번호', p_naver_order_id,
        '디자인접수링크', p_intake_url
      ),
      case when length(coalesce(v_phone, '')) >= 10 then 'pending' else 'skipped_no_phone' end
    );
  else
    update public.naver_design_sessions
    set buyer_name = coalesce(nullif(trim(p_buyer_name), ''), buyer_name),
        buyer_phone = coalesce(nullif(trim(p_buyer_phone), ''), buyer_phone),
        receiver_phone = coalesce(nullif(trim(p_receiver_phone), ''), receiver_phone),
        updated_at = now()
    where id = v_session_id;
  end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    if nullif(trim(v_item->>'product_order_id'), '') is null then
      continue;
    end if;
    select c.job_id into v_job_id
    from public.naver_design_job_claims c
    where c.product_order_id = v_item->>'product_order_id';
    if v_job_id is not null then
      if nullif(v_item->>'local_product_id', '') is not null then
        update public.naver_design_jobs j
        set local_product_id = coalesce(j.local_product_id, nullif(v_item->>'local_product_id', '')::uuid),
            status = case when j.status = 'needs_mapping' then 'draft' else j.status end,
            updated_at = now()
        where j.id = v_job_id;
      end if;
      continue;
    end if;

    v_job_was_created := false;
    select j.id into v_job_id
    from public.naver_design_jobs j
    where j.session_id = v_session_id
      and j.group_key = v_item->>'group_key'
    for update;

    if v_job_id is null then
      insert into public.naver_design_jobs (
        session_id, group_key, local_product_id, color_code, product_name,
        option_summary, quantity, product_order_ids, status
      ) values (
        v_session_id,
        coalesce(nullif(trim(v_item->>'group_key'), ''), v_item->>'product_order_id'),
        nullif(v_item->>'local_product_id', '')::uuid,
        nullif(trim(v_item->>'color_code'), ''),
        coalesce(nullif(trim(v_item->>'product_name'), ''), '네이버 상품'),
        nullif(trim(v_item->>'option_summary'), ''),
        greatest(coalesce((v_item->>'quantity')::integer, 0), 0),
        array[v_item->>'product_order_id'],
        case when nullif(v_item->>'local_product_id', '') is null then 'needs_mapping' else 'draft' end
      ) returning id into v_job_id;
      v_job_was_created := true;
    else
      update public.naver_design_jobs
      set quantity = quantity + greatest(coalesce((v_item->>'quantity')::integer, 0), 0),
          product_order_ids = case
            when v_item->>'product_order_id' = any(product_order_ids) then product_order_ids
            else array_append(product_order_ids, v_item->>'product_order_id')
          end,
          option_summary = coalesce(option_summary, nullif(trim(v_item->>'option_summary'), '')),
          updated_at = now()
      where id = v_job_id;
    end if;

    insert into public.naver_design_job_claims(product_order_id, job_id)
    values (v_item->>'product_order_id', v_job_id);
    v_items_claimed := v_items_claimed + 1;
    if v_job_was_created then v_jobs_created := v_jobs_created + 1; end if;
  end loop;

  update public.naver_design_sessions s
  set job_count = (select count(*) from public.naver_design_jobs j where j.session_id = s.id),
      submitted_job_count = (select count(*) from public.naver_design_jobs j where j.session_id = s.id and j.status in ('submitted', 'reviewed', 'approved')),
      updated_at = now()
  where s.id = v_session_id;

  insert into public.naver_design_events(session_id, event_type, payload)
  values (v_session_id, 'order_ingested', jsonb_build_object('items_claimed', v_items_claimed));

  return query select v_session_id, v_session_created, v_jobs_created, v_items_claimed;
end;
$$;

create or replace function public.claim_naver_design_notifications(p_limit integer default 20)
returns setof public.naver_design_notification_outbox
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  return query
  with candidates as (
    select id
    from public.naver_design_notification_outbox
    where (
      status in ('pending', 'failed')
      or (status = 'sending' and claimed_at < now() - interval '10 minutes')
    )
      and next_attempt_at <= now()
      and attempts < 5
    order by created_at
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 20), 100))
  )
  update public.naver_design_notification_outbox o
  set status = 'sending',
      claimed_at = now(),
      attempts = attempts + 1,
      updated_at = now()
  from candidates c
  where o.id = c.id
  returning o.*;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'naver_design_sessions',
    'naver_design_jobs',
    'naver_design_job_claims',
    'naver_design_assets',
    'naver_design_events',
    'naver_design_notification_outbox'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from public, anon, authenticated', table_name);
    execute format('grant select, insert, update, delete on table public.%I to service_role', table_name);
  end loop;
end $$;

revoke all on function public.ingest_naver_design_order(text, text, text, text, text, text, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.ingest_naver_design_order(text, text, text, text, text, text, text, jsonb)
  to service_role;
revoke all on function public.claim_naver_design_notifications(integer)
  from public, anon, authenticated;
grant execute on function public.claim_naver_design_notifications(integer)
  to service_role;

grant usage, select on all sequences in schema public to service_role;
