-- 네이버 스마트스토어 운영 원장.
-- 모든 접근은 관리자 인증 뒤 service_role 서버 경로에서만 수행한다.

create table if not exists public.naver_product_mappings (
  id bigint generated by default as identity primary key,
  local_product_id uuid references public.products(id) on delete set null,
  origin_product_no bigint not null unique,
  channel_product_no bigint unique,
  naver_product_name text not null,
  status_type text,
  sale_price integer check (sale_price is null or sale_price >= 0),
  stock_quantity integer check (stock_quantity is null or stock_quantity >= 0),
  raw_summary jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_naver_product_mappings_local
  on public.naver_product_mappings(local_product_id)
  where local_product_id is not null;

create table if not exists public.naver_product_orders (
  product_order_id text primary key,
  naver_order_id text not null,
  product_order_status text,
  claim_status text,
  last_changed_type text,
  last_changed_at timestamptz,
  order_date timestamptz,
  payment_date timestamptz,
  origin_product_no bigint,
  channel_product_no bigint,
  product_name text,
  option_name text,
  quantity integer not null default 0 check (quantity >= 0),
  unit_price integer not null default 0 check (unit_price >= 0),
  total_payment_amount integer not null default 0 check (total_payment_amount >= 0),
  buyer_name text,
  buyer_tel text,
  receiver_name text,
  receiver_tel1 text,
  receiver_tel2 text,
  receiver_zip_code text,
  receiver_base_address text,
  receiver_detail_address text,
  shipping_memo text,
  delivery_method text,
  delivery_company_code text,
  tracking_number text,
  dispatched_at timestamptz,
  logen_registered_at timestamptz,
  naver_dispatched_at timestamptz,
  raw_data jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_naver_product_orders_order
  on public.naver_product_orders(naver_order_id);
create index if not exists idx_naver_product_orders_status_changed
  on public.naver_product_orders(product_order_status, last_changed_at desc);
create index if not exists idx_naver_product_orders_payment
  on public.naver_product_orders(payment_date desc)
  where payment_date is not null;

create table if not exists public.naver_shipments (
  id bigint generated by default as identity primary key,
  naver_order_id text not null unique,
  fix_take_no text not null unique,
  product_order_ids text[] not null,
  box_qty integer not null default 1 check (box_qty between 1 and 99),
  status text not null default 'pending' check (status in ('pending', 'registered', 'invoiced', 'dispatched', 'error')),
  logen_registered_at timestamptz,
  tracking_number text,
  extra_tracking_numbers text[] not null default '{}'::text[],
  naver_dispatched_at timestamptz,
  error_message text,
  raw_logen jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_naver_shipments_status
  on public.naver_shipments(status, updated_at desc);

create table if not exists public.naver_settlement_daily (
  settlement_key text primary key,
  settlement_date date,
  settlement_type text,
  merchant_name text,
  payment_method text,
  sale_amount numeric(18, 2) not null default 0,
  settlement_amount numeric(18, 2) not null default 0,
  commission_amount numeric(18, 2) not null default 0,
  raw_data jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_naver_settlement_daily_date
  on public.naver_settlement_daily(settlement_date desc);

create table if not exists public.naver_qnas (
  question_id bigint primary key,
  product_id bigint,
  product_name text,
  question text,
  answer text,
  answered boolean not null default false,
  writer_id_masked text,
  question_created_at timestamptz,
  raw_data jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_naver_qnas_answered_created
  on public.naver_qnas(answered, question_created_at desc);

create table if not exists public.naver_sync_runs (
  id bigint generated by default as identity primary key,
  sync_type text not null,
  status text not null check (status in ('running', 'success', 'failed', 'skipped')),
  fetched_count integer not null default 0 check (fetched_count >= 0),
  upserted_count integer not null default 0 check (upserted_count >= 0),
  error_message text,
  detail jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists idx_naver_sync_runs_type_started
  on public.naver_sync_runs(sync_type, started_at desc);

create table if not exists public.naver_sync_cursors (
  cursor_key text primary key,
  cursor_value text not null,
  updated_at timestamptz not null default now()
);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'naver_product_mappings',
    'naver_product_orders',
    'naver_shipments',
    'naver_settlement_daily',
    'naver_qnas',
    'naver_sync_runs',
    'naver_sync_cursors'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
    execute format('grant select, insert, update, delete on table public.%I to service_role', table_name);
  end loop;
end $$;

grant usage, select on all sequences in schema public to service_role;
